FROM wordpress:latest

# Set environment variables (example)
# ENV WORDPRESS_DB_HOST=mariadb-service:3306
# ENV WORDPRESS_DB_NAME=wordpress
# ENV WORDPRESS_DB_USER=wp_user
# ENV WORDPRESS_DB_PASSWORD=wp_password

